# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-gist
# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: # jekyll-seo-tag > Owners twitter username
author: Kranti S Wadhai # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Kranti Wadhai # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)

    - https://github.com/wkranti

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: India # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Forced Alignment" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=1039"

# 6. Jekyll collections settings

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Kranti S Wadhai" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/arch.png" # Site logo, also used in jekyll-seo-tag
description: "This site is product of Google Summer Of Code 2018 project with Red Hen Lab as mentor Organization.Project focus on extending language support to Gentle" # Site description and default description, also used in jekyll-seo-tag
url: "https://wkranti.github.io" # Site url, also used in jekyll-seo-tag
baseurl:
repo: "https://github.com/wkranti"
email: "wkranti8@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/aa.jpg"  # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
service_worker : false
# 8. Site navigation
navigation_header:
  About: /
  Project: /project/
  Blog: /blog/
  Team: /team/
  Search: /search/
  Fork Gentle: https://github.com/lowerquality/gentle

navigation_footer:
  Created by Kranti Wadhai: https://github.com/wkranti

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired

  GitHub: https://github.com/wkranti
remote_theme: daviddarnes/alembic

#sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
#  Twitter: "#0d94e7"
#  facebook: "#3B5998"
#  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
